"""empty message

Revision ID: 300398a9e70c
Revises: 6bcba1d1dc9d
Create Date: 2025-09-24 10:22:35.953369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300398a9e70c'
down_revision = '6bcba1d1dc9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint('follower_user_to_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follower_user_to_id_fkey', 'post', ['user_to_id'], ['id'])

    # ### end Alembic commands ###
